version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    working_directory: ~/builds
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build
      - run: ./deploy/fetch.sh
